name: Pull To Develop Noetic
on: 
  pull_request:
    branches: 
      - develop

jobs:
    build_noetic:
      runs-on: ubuntu-latest
      container:
        image: osrf/ros:noetic-desktop
      #if: github.event_name == 'push'
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v1
        - name: Build Workspace
          run: |
            sudo apt-get update -y
            sudo apt install python3-catkin-tools python3-osrf-pycommon
            source /opt/ros/noetic/setup.bash
            cd ./catkin_ws
            rosdep update
            rosdep install -y --from-paths . --ignore-src
            catkin build
          shell: bash