name: Build & Test ROS Noetic WS
on: 
  push:
    branches:
      - master
    paths:
      - "catkin_ws/**"
  pull_request:
    types: [closed, opened, reopened]

jobs:
  Build_Test_ROS_Noetic:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:noetic-desktop
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Build Workspace
        run: |
          sudo apt-get update -y
          sudo apt install python3-catkin-tools python3-osrf-pycommon
          source /opt/ros/noetic/setup.bash
          cd ./catkin_ws
          rosdep update
          rosdep install -y --from-paths . --ignore-src
          catkin build
        shell: bash