name: Setup ROS/ROS2 Runners
on: push

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic foxy
      - run: vcs --help
      - run: "source /opt/ros/galactic/setup.bash && ros2 run --help"
      - run: "source /opt/ros/noetic/setup.bash && rosnode --help"