name: Build & Test ROS/ROS2
on: push

jobs:
  Build_Test_ROS2:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:foxy-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pipeline
        run: |
          source /opt/ros/foxy/setup.bash
          cd ./test/ros2_ws
          rosdep install -y --from-paths . --ignore-src
          colcon build --symlink-install
        shell: bash